### ISSUE TITLE
How to aggregate OCM crds in one api

### ISSUE THREAD

**Issue by softcane** [open-cluster-management-io/ocm#1007]
I'm working with the Open Cluster Management Project. It's a powerful tool, but it includes many CRDs, such as ManifestWorkReplicaSet, ManifestWork (in the cluster namespace), PlacementDecision, and ManagedClusterSetBinding.

We're not planning to use this project to manage deployments across clusters. Instead, we see it as a platform control plane component mainly to keep track of clusters and manage tenant configurations, while we handle orchestration ourselves.

I want to create a new custom resource called TenantDeploymentRecord using Kube Builder. This CRD should combine information from all the existing CRDs mentioned above. It should also update automatically whenever any of those CRDs change.

Example snippet

```
apiVersion: my.control-plane.api.v1alpha1/v1alpha1
kind: TenantDeploymentRecord
metadata:
  name: sample-tenant
spec:
  environment: prod
  clusterType: api
  placementRef:
    - edge-01
    - edge-02
  workload:
    - clusterName: edge-01
      manifest:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: frontend
        spec:
          replicas: 3
          selector:
            matchLabels: {app: frontend}
          template:
            metadata:
              labels: {app: frontend}
            spec:
              containers:
                - name: nginx
                  image: nginx:1.21
    - clusterName: edge-02
      manifest:
      workloads:
        - manifest:
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: shared-config
            data:
              LOG_LEVEL: info
```

I’d appreciate any feedback or suggestions from the community.
