### ISSUE TITLE
EKS DeleteAccessEntry 404 error when attempting to delete an EKS ManagedCluster from the hub

### ISSUE THREAD

**Issue by ahmad-ibra** [open-cluster-management-io/ocm#1010]
**Describe the bug**
When trying to delete an EKS `ManagedCluster` using `kubectl delete managedcluster <managed-cluster-name>`. The `ManagedCluster` never ends up being cleaned up. Errors are observed in the `cluster-manager-registration-controller` indicating that the controller is failing to find and delete Access Entries.

**To Reproduce**

First configure a healthy MultiCluster.
1. Create a hub and spoke EKS clusters. (in my case they are both in `us-west-2` and in the same AWS account)
2. Follow the steps 1-4 in the following guide (note that step 5 was skipped because `ManagedClusterAutoApproval=true` and the spoke was automatically accepted: https://github.com/open-cluster-management-io/ocm/blob/main/solutions/joining-hub-and-spoke-with-aws-auth/README.md
3. Validate that the MultiCluster is healthy by inspecting its conditions:
```yaml
  conditions:
  - lastTransitionTime: "2025-05-27T23:44:30Z"
    message: Accepted by hub cluster admin
    reason: HubClusterAdminAccepted
    status: "True"
    type: HubAcceptedManagedCluster
  - lastTransitionTime: "2025-05-27T23:44:32Z"
    message: Managed cluster joined
    reason: ManagedClusterJoined
    status: "True"
    type: ManagedClusterJoined
  - lastTransitionTime: "2025-05-27T23:59:30Z"
    message: Registration agent stopped updating its lease.
    reason: ManagedClusterLeaseUpdateStopped
    status: Unknown
    type: ManagedClusterConditionAvailable
  - lastTransitionTime: "2025-05-27T23:44:32Z"
    message: The clock of the managed cluster is synced with the hub.
    reason: ManagedClusterClockSynced
    status: "True"
    type: ManagedClusterConditionClockSynced
```

Now try to cleanup the MultiCluster
1. Run `clusteradm unjoin --cluster-name <my-spoke-cluster> --purge-operator=true --kubeconfig /tmp/kubeconfig2792266478` and see all OCM resources on the spoke are deleted as expected
2. Run `kubectl delete managedcluster <managed-cluster-name>`

Finally observe the results of the deletion
1. A deletionTimestamp gets added to the hubs ManagedCluster resource as expected, but the finalizer is never removed.
2. See the following error logs repeated in the `cluster-manager-registration-controller`
```
E0527 23:55:49.385699       1 hub_driver.go:316] "Failed to delete Access Entry for HubClusterName" err="operation error EKS: DeleteAccessEntry, https response error StatusCode: 404, RequestID: b76929d5-5d2a-4531-b063-95f4c2efc9bb, ResourceNotFoundException: The specified principalArn could not be found. You can view your available access entries with 'list-access-entries'." HubClusterName="hub-eks-test-8"

E0527 23:55:49.385747       1 base_controller.go:277] "Unhandled Error" err="\"ManagedClusterController\" controller failed to sync \"spoke-eks-test\", err: operation error EKS: DeleteAccessEntry, https response error StatusCode: 404, RequestID: b76929d5-5d2a-4531-b063-95f4c2efc9bb, ResourceNotFoundException: The specified principalArn could not be found. You can view your available access entries with 'list-access-entries'."
```

3. Confirm that the cluster and access entries actually do exist
```bash
❯ aws eks list-clusters --region us-west-2 | jq
{
  "clusters": [
    "hub-eks-test-8",
    "spoke-eks-test-8"
  ]
}

❯ aws eks list-access-entries --cluster-name hub-eks-test-8 --region us-west-2 | jq
{
  "accessEntries": [
    "arn:aws:iam::<REDACTED>:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS",
    "arn:aws:iam::<REDACTED>:role/eksctl-hub-eks-test-8-nodegroup-ng-NodeInstanceRole-L1hoSOFvhLkG",
    "arn:aws:iam::<REDACTED>:user/ahmad"
  ]
}
```

**Expected behavior**
When a deletionTimestamp is added to an EKS `ManagedCluster`, IAM roles and Access Entries should be succesfully deleted allowing the cleanup of the EKS `ManagedCluster` to complete.
https://github.com/open-cluster-management-io/ocm/blob/4cbb12d5a2622ce5a698d5e07530f76166d3a922/pkg/registration/register/aws_irsa/hub_driver.go#L87

**Environment ie: OCM version, Kubernetes version and provider:**
OCM_VERSION: v0.16.1

**Additional context**
I think this may have to do with the AWS region my resources were created in. It's not entirely clear how the `eksClient` would know which region to delete resources from.
