### ISSUE TITLE
AppliedManifestFailed when creating ManifestWorks with jobs

### ISSUE THREAD

**Issue by josecastillolema** [open-cluster-management-io/OCM#118]
When creating simple ManifestWorks with jobs, i.e.:
```
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  namespace: cluster1
  name: simple-job
spec:
  workload:    
    manifests:
      - apiVersion: batch/v1
        kind: Job
        metadata:
          name: simple-job
          namespace: default
        spec:
          template:
            spec:
              containers:
              - name: kubectl
                image: quay.io/sighup/kubectl-kustomize:1.21.6_3.9.1
                command: ["/bin/sh", "-c"]
                args:
                  - pwd
              restartPolicy: Never
          backoffLimit: 0
```

The job gets correctly created in the ManagedCluster:
```
% k get job --context kind-cluster1
NAME         COMPLETIONS   DURATION   AGE
simple-job   1/1           5s         5m24s

% k describe job simple-job  --context kind-cluster1
...
Events:
  Type    Reason            Age    From            Message
  ----    ------            ----   ----            -------
  Normal  SuccessfulCreate  5m34s  job-controller  Created pod: simple-job-sj76d
  Normal  Completed         5m29s  job-controller  Job completed
```

However for some reason the ManifestWork reports **AppliedManifestFailed**: 

```
Conditions:
        Last Transition Time:  2022-12-05T12:36:38Z
        Message:               Failed to apply manifest: Job.batch "simple-job" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string(nil): 'selector' does not match template 'labels', spec.selector: Invalid value: "null": field is immutable, spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"kubectl", Image:"quay.io/sighup/kubectl-kustomize:1.21.6_3.9.1", Command:[]string{"/bin/sh", "-c"}, Args:[]string{"pwd"}, WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:"Never", TerminationGracePeriodSeconds:(*int64)(0xc008138068), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc0063d06c0), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil), OS:(*core.PodOS)(nil)}}: field is immutable]
        Reason:                AppliedManifestFailed
        Status:                False
        Type:                  Applied
        Last Transition Time:  2022-12-05T12:36:38Z
        Message:               Resource is available
        Reason:                ResourceAvailable
        Status:                True
        Type:                  Available
        Last Transition Time:  2022-12-05T12:36:38Z
        Message:               
        Reason:                NoStatusFeedbackSynced
        Status:                True
        Type:                  StatusFeedbackSynced

```

**Comment by josecastillolema** [comment]
I think this may be preventing the ManifestWork to properly report **FeedbackRules** (please correct me if I am wrong):
```
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  namespace: cluster1
  name: simple-job
spec:
  manifestConfigs:
    - resourceIdentifier:
        group: batch
        resource: job
        namespace: default
        name: simple-job
      feedbackRules:
        - type: JSONPaths
          jsonPaths:
            - name: succeeded
              path: '.status.succeeded'
  workload:    
    manifests:
      - apiVersion: batch/v1
        kind: Job
        metadata:
          name: simple-job
          namespace: default
        spec:
          template:
            spec:
              containers:
              - name: kubectl
                image: quay.io/sighup/kubectl-kustomize:1.21.6_3.9.1
                command: ["/bin/sh", "-c"]
                args:
                  - pwd
              restartPolicy: Never
          backoffLimit: 0
```

No **status feedback** whatsover:
`      Status Feedback:
`

**Comment by mikeshng** [comment]
I think it was successfully applied based on the original spec but because it auto populated some other spec fields the subsequent update apply is no longer successful.
@qiujian16 @zhujian7 do we doc this?

**Comment by qiujian16** [comment]
it should not impact statusfeedback as long as the condition is available. I think the configuration missing version part:

```
manifestConfigs:
    - resourceIdentifier:
        group: batch
        version: v1
        resource: job
        namespace: default
        name: simple-job
```

for apply part, job is a bit different due to default label/selectors. we should document it. And you could try using serversideapply configuration. something like this: 

```
manifestConfigs:
    - resourceIdentifier:
        group: batch
        version: v1
        resource: job
        namespace: default
        name: simple-job
      feedbackRules:
        - type: WellKnownStatus
      updateStrategy:
        type: ServerSideApply
```
