### ISSUE TITLE
Placement API to allow multiple ManifestWorks to be assigned to the same cluster

### ISSUE THREAD

**Issue by aii-nozomu-oki** [open-cluster-management-io/ocm#155]
Hi, I'm working on building a [multi-cluster autoscaler](https://github.com/open-cluster-management-io/enhancements/issues/94).
One idea is to create custom resources on top of ManifestWork, like Deployment for Pod, and scale the replicas of it.
I intend to have the custom resource controller generate name-[UUID] ManifestWorks.

The problem with building a multi-cluster autoscaler based on the above idea is that the Placement API doesn't allow multiple ManifestWork assignments to the same cluster.

If there are cluster-1 and cluster-2, and numberOfClusters is 3, the PlacementDecision would be as follows.

```yaml
status:
  decisions:
  - clusterName: cluster-1
    reason: ""
  - clusterName: cluster-2
    reason: ""
```

Are there any plans to add `numberOfResources` param, for example, in the future to allow for it?

In that case, the PlacementDecision would be as follows.

```yaml
status:
  decisions:
  - clusterName: cluster-1
    resources: 2
    reason: ""
  - clusterName: cluster-2
    resources: 1
    reason: ""
```

If that is not planned, I would build a custom scheduler.

**Comment by aii-nozomu-oki** [comment]
In my example, "resource" means ManifestWork. So `numberOfResources `means `numberOfManifestWorks`.
Probably the following example better expresses my request.

If there are cluster-1 and cluster-2, and numberOfManifestWorks is 3:

```yaml
status:
  decisions:
  - clusterName: cluster-1
    manifestWorks: 2
    reason: ""
  - clusterName: cluster-2
    manifestWorks: 1
    reason: ""
```

In this example, two ManifestWorks will be placed in cluster-1 and one ManifestWork in cluster-2.

My request aligns with https://github.com/open-cluster-management-io/ocm/issues/134 in modifying the PlacementDecision's output, but it differs in proposing a major change to the Placement API.
