### ISSUE TITLE
Offer a general purpose ReplicatedResource for clusterset

### ISSUE THREAD

**Issue by tamalsaha** [open-cluster-management-io/ocm#307]
**Describe the enhancement**
Currently there are case-by-case resources to replicate Resources in the Hub cluster to spoke cluster namespaces. Examples are:

- ManifestWorkResplicaSet
- ClusterAddonManager
- Potentially one for ManagedSeviceAccount https://github.com/open-cluster-management-io/managed-serviceaccount/issues/90
- For future addons that will also have a similar CRD like `ManagedSeviceAccount`

Will it make sense to support one general purpose `ManagedResourceSet` that will take a Placement and `resourceTemplate` and replicate that into the cluster namespaces according to placement logic. This can handle all the above cases as far as I can understand ( i have not thought through it deeply).

I am curious if this something like this was considered? If not, is this an option?

Thanks.

**Comment by mikeshng** [comment]
Hi @tamalsaha

I will let other maintainers chime in on your suggestion.

But just FYI I had a similar requirement and @JustinKuli was able provide me with a clever solution here: https://gist.github.com/JustinKuli/b66d1096e1262a0bc51f8ff8f29169f8 using ocm policy addon.

> The idea is to use a Placement and a Policy to distribute a resource to managed cluster namespaces on a hub cluster, not to the actual managed clusters.

Let me know if you have any questions.

**Comment by qiujian16** [comment]
ManifestWorkResplicaSet and ClusterAddonManager has slightly different purposes. 

ManifestWorkResplicaSet is for the purpose of user can "replicate manifests to multiple clusters".
`ClusterAddonManager` is for the addon developer to develop an addon, then user can choose to enable the addon cluster by cluster, or by a certain strategy.
`ManagedSeviceAccount` seems to me also different, it meant to ask each spoke cluster provide some credential to access them. 

The ManagedResourceSet seems to be quite similar as what ManifestWorkResplicaSet did?

**Comment by tamalsaha** [comment]
I was referring to the part where the controller for ManifestWorkResplicaSet,  ClusterAddonManager, higher-level-of-ManagedSeviceAccount are all performing one general operation: create the individual ManifestWork, ManagedClusterAddon, ManagedServiceAccount object by copying the the parent object into the cluster namespaces. This general part can be offered a single resource. The template for the parent object can have the full underlying object spec (like PodTemplate).

```yaml
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetResource
metadata:
  name: <name>
  namespace: <ns>
spec:
  placementRefs:
    - name: placement-byname # Name of a created Placement
  template:
    apiVersion:
    kind: 
    metadata:
      ...
   spec:
      ...
```

`spec.template.apiVersion` and `spec.template.kind` can dictate whether the underlying object is a ManfestWork / ManagedClusterAddon / ManagedServiceAccount .
