### ISSUE TITLE
support setting the kube-api-burst/kube-api-qps parameter through the klusterlet operator

### ISSUE THREAD

**Issue by sacr0** [open-cluster-management-io/ocm#331]
All controllers allow for the option to set the parameters `--kube-api-burst` and `--kube-api-qps` as they are common options [1]. But it does not seem possible to pass these to the klusterlet operator, to get these parameters applied to the klusterlet controllers. 

I would expect that I can configure these settings through the klusterlet custom resource similar to `clientCertExpirationSeconds` [2]. 

At the moment I have no way of configuring these two settings, other than disabling the klusterlet operator and updating the deployments (for example the work-agent deployment) manually. So I would very much like to have this implemented similar to the way this is done for `clientCertExpirationSeconds`.

[1] https://github.com/open-cluster-management-io/ocm/blob/main/pkg/common/options/options.go#L43
[2] https://github.com/open-cluster-management-io/ocm/blob/main/deploy/klusterlet/config/crds/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml#L179

**Comment by zhiweiyin318** [comment]
added flags in klusterlet CRD. for example: 
```
spec:
   workConfiguration:
       kubeAPIQPS: 50
       kubeAPIBurst: 100
  registrationConfiguration:
       kubeAPIQPS: 50
       kubeAPIBurst: 100
```
