### ISSUE TITLE
Should validate the `registration.customSigner.signerName` in the addontemplate 

### ISSUE THREAD

**Issue by skeeey** [open-cluster-management-io/ocm#382]
**Describe the bug**
If I used a invalid signerName, e.g. `xxx-addon`, there are no any hints  to specify this, unless checking the registration agent log

```
Invalid value: "xxx-addon": must be a fully qualified domain and path of the form 'example.com/signer-name'
```

**To Reproduce**
```
 registration:
  - type: CustomSigner
    customSigner:
      signerName: xxx-addon
      signingCA:
        name: xxxx
```

**Expected behavior**
Validate this when I create the addontemplate
