### ISSUE TITLE
Permission setting for work agent do not support MutatingWebhookConfiguration

### ISSUE THREAD

**Issue by pdettori** [open-cluster-management-io/ocm#384]
**Describe the bug**
A MutatingWebhookConfiguration cannot be deployed using ManifestWork.

**To Reproduce**
Create a ManifestWork with a MutatingWebhookConfiguration and observe the ManifestWork conditions:
```
manifests:
    - conditions:
      - lastTransitionTime: "2024-01-23T21:36:54Z"
        message: 'Failed to apply manifest: mutatingwebhookconfigurations.admissionregistration.k8s.io
          "kar-injector-webhook" is forbidden: User "system:serviceaccount:open-cluster-management-agent:klusterlet-work-sa"
          cannot get resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io"
          at the cluster scope'
        reason: AppliedManifestFailed
```        

**Expected behavior**
Since MutatingWebhookConfiguration is a widely used resource in many Kubernetes projects, it should deploy out of the box. 

**Environment ie: OCM version, Kubernetes version and provider:**

```
$ clusteradm version
client          version :v0.7.2
server release  version :v1.27.1
default bundle  version :0.12.0
```
This was tested on kind:

```
$ kind version
kind v0.19.0 go1.20.5 darwin/arm64
```

**Additional context**

This could be solved by adding the following clusterrole and clusterrolebinding, but it seems a lot of extra work for a resource that is part of the common set of resources in kube.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klusterlet-mutatingwebhook-access
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: klusterlet-mutatingwebhook-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: klusterlet-mutatingwebhook-access
subjects:
- kind: ServiceAccount
  name: klusterlet-work-sa
  namespace: open-cluster-management-agent
```
