### ISSUE TITLE
ManifestWork set fileManager to "work" instead of "work-agent" when use "Update" type of updateStrategy

### ISSUE THREAD

**Issue by haowells** [open-cluster-management-io/ocm#586]
**Describe the bug**
ManifestWork set fileManager to "work" instead of "work-agent" when use "Update" type of updateStrategy

**To Reproduce**
1. create manifestwork with this manifestConfigs 
```
spec:
  manifestConfigs:
  - feedbackRules:
    - jsonPaths:
      - name: healthStatus
        path: .status.health.status
      type: JSONPaths
    - jsonPaths:
      - name: syncStatus
        path: .status.sync.status
      type: JSONPaths
    resourceIdentifier:
      group: argoproj.io
      name: guestbook
      namespace: argocd-tess
      resource: applications
    updateStrategy:
      type: Update
```
2.  After payload (argo application) object applied to managed cluster. use `kubectl get --show-managed-fields` check resource manager field
```
  manager: work
  operation: Update
```
3. Change manifestConfigs to `type: ServerSideApply`,  use `kubectl get --show-managed-fields` check resource manager fields again, there is new manager `work-agent` 
```
  manager: work-agent
  operation: Apply

```
**Expected behavior**
manager name should be same  between "Update" and "ServerSideApply" strategy

**Environment ie: OCM version, Kubernetes version and provider:**
ocm: 0.14.0
k8s: v1.27
**Additional context**
