### ISSUE TITLE
Allow addons to be installed by label, but also manually

### ISSUE THREAD

**Issue by tesshuflower** [open-cluster-management-io/ocm#616]
**Describe the enhancement**

I'm considering this an enhancement request, but we do have some functionality that was removed between v0.9.0 and v0.10.0 of the `addon-framework`.

Essentially my use-case (for the ACM volsync-addon-controller which uses the addon-framework) is that users are able to deploy the addon to managed clusters in 2 ways:

1. Users can add a specific label to a `ManagedCluster` resource, and then the `ManagedClusterAddOn` resource is created automatically for them in the managedcluster namespace on the hub.
2. Users can manually create the `ManagedClusterAddOn`.

This has been the case for quite a few ACM releases.

To achieve this, I have the following in my addon setup:

```
agent.AgentAddonOptions{
		AddonName: addonName,
		InstallStrategy: agent.InstallByLabelStrategy(
			"",
			metav1.LabelSelector{
				MatchLabels: map[string]string{
					ManagedClusterInstallVolSyncLabel: ManagedClusterInstallVolSyncLabelValue,
				},
			},
		),
```

but now in v0.10.0 the InstallByLabelStrategy has been removed.

Is there something I can do to get this functionality back? For the meantime I'm not updating to the addon-framework v0.10.0.

**Comment by tesshuflower** [comment]
I'm not sure I understand the "Placements" install strategy - will this work for a label? Or would someone need to create a placement that then looks for a label selector?

**Comment by haoqing0110** [comment]
@tesshuflower 

With "Placements" install strategy, you will need to create 2 resources as below, 1 cma and 1 placement with label selector. 
With this defined, the user can no longer manually create mca unless changes the type to Manual. 

```
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: helloworld
  annotations:
    addon.open-cluster-management.io/lifecycle: "addon-manager"
spec:
  addOnMeta:
    displayName: helloworld
  installStrategy:
    type: Placements
    placements:
    - name: placement-test
      namespace: default
```
```
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-test
  namespace: default
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            purpose: test
 ```
