### ISSUE TITLE
Support configuring proxy for template type addons

### ISSUE THREAD

**Issue by zhujian7** [open-cluster-management-io/ocm#761]
**Describe the enhancement**

Request using the [AddonDeploymentConfig](https://github.com/open-cluster-management-io/api/blob/0ba6809d0ae2767b64c7fe29a0b998702d0af7b9/addon/v1alpha1/types_addondeploymentconfig.go#L53) to configure proxy(http proxy, https proxy, no proxy) for template type addons.

```
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: proxy-deploy-config
  namespace: multicluster-engine
spec:
  proxyConfig:
    httpProxy: "http://test.com"
    httpsProxy: "https://test.com"
    noProxy: "http://testno.com"
    caBundle: "fakeBundle"
```
